version: '3.8'

services:
  main:
    image: ${DOCKER_REGISTRY-}blogapppresentation
    build:
      context: .
      dockerfile: src/BlogApp.Presentation/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=BlogAppDb;User=sa;Password=Sasasa12;MultipleActiveResultSets=true"
    ports:
      - "8080:80"
    depends_on:
      - db
      - auth
    restart: on-failure

  auth:
    image: ${DOCKER_REGISTRY-}blogappauthorization
    build:
      context: .
      dockerfile: src/BlogApp.Authorization/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=BlogAppAuthDb;User=sa;Password=Sasasa12;MultipleActiveResultSets=true"
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      - "SA_PASSWORD=Sasasa12"
      - "ACCEPT_EULA=Y"